module.exports = {
  version: '0.2',
  language: 'es-ES,en-US',
  words: [
    'worktree',
    'worktrees',
    'pnpm',
    'nextjs',
    'supabase',
    'lucide',
    'zustand',
    'papaparse',
    'commitlint',
    'lirantal',
    'lockfile',
    'rseidelsohn',
    'depcheck',
    'lhci',
    'gitleaks',
    'cyclonedx',
    'SLSA',
    'SARIF',
    'corepack',
    'dedupe',
    'typecheck',
    'tailwindcss',
    'autoprefixer',
    'postcss',
    'Smurf',
    'Noriega'
  ],
  ignorePaths: [
    'node_modules',
    'dist',
    '.next',
    '.turbo',
    'build',
    'coverage',
    'pnpm-lock.yaml',
    '*.log',
    '.git',
    '.husky',
    'playwright-report',
    'test-results'
  ]
};
