name: Reporte de seguridad (privado)
description: No publiques PII ni secretos.
title: "[SEC] "
labels: ["security"]
assignees: ["hekouo"]
body:
  - type: markdown
    attributes:
      value: |
        **No pegues secretos aquí.**
  - type: textarea
    id: desc
    attributes:
      label: Descripción
      description: ¿Qué viste? ¿Cómo se reproduce?
      placeholder: Pasos, URLs, stacktrace.
    validations:
      required: true
