// Auto-generated by fix script
export type Gtag =
  | ((cmd: "config", id: string, params?: Record<string, unknown>) => void)
  | ((cmd: "event", name: string, params?: Record<string, unknown>) => void)
  | ((cmd: "js", date: Date) => void);

declare global {
  interface Window {
    gtag?: (...args: Parameters<Gtag>) => void;
  }
}
export {};
